#!/bin/sh

set -e

case "$1" in
    configure)
	adduser --system --home /var/lib/digabi-repository --shell /bin/sh --group digabi-repository || true

	mkdir -p /var/log/digabi-repository
	if id -u digabi-repository > /dev/null 2>&1
	then
	    chown digabi-repository:digabi-repository /var/log/digabi-repository	
	fi

	su digabi-repository -c "gpg --import /etc/digabi-repository/trusted.gpg.d/*.gpg"
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
